config/routes.rb
JoberEngine::Engine.routes.draw do
  root to: 'jobs#index'
  resources :jobs
end

app/models/jober_engine/application_record.rb
module JoberEngine
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/jober_engine/application_controller.rb
module JoberEngine
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/jober_engine/jobs_controller.rb
require_dependency "jober_engine/application_controller"

module JoberEngine
  class JobsController < ApplicationController
    before_action :set_job, only: [:show, :edit, :update, :destroy]

    def index
      @jobs = JoberEngine.job_class.all
    end

    def show
    end

    def new
      @job = JoberEngine.job_class.new
    end

    def edit
    end

    def create
      @job = JoberEngine.job_class.new(job_params)

      if @job.save
        redirect_to @job, notice: 'Job was successfully created.'
      else
        render :new
      end
    end

    def update
      if @job.update(job_params)
        redirect_to @job, notice: 'Job was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @job.destroy
      redirect_to jobs_url, notice: 'Job was successfully destroyed.'
    end

    private

    def set_job
      @job = JoberEngine.job_class.find(params[:id])
    end

    def job_params
      params.require(:job).permit(
        :priority, :attempts, :handler, :last_error, :run_at, :locked_at,
        :failed_at, :locked_by, :queue
      )
    end
  end
end

app/helpers/jober_engine/application_helper.rb
module JoberEngine
  module ApplicationHelper
  end
end

app/helpers/jober_engine/jobs_helper.rb
module JoberEngine
  module JobsHelper
  end
end

app/views/jober_engine/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :priority, class: 'form-label' %>
    <%= form.text_field :priority, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :attempts, class: 'form-label' %>
    <%= form.text_field :attempts, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :handler, class: 'form-label' %>
    <%= form.text_field :handler, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :last_error, class: 'form-label' %>
    <%= form.text_field :last_error, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :run_at, class: 'form-label' %>
    <%= form.datetime_select :run_at, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :locked_at, class: 'form-label' %>
    <%= form.datetime_select :locked_at, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :failed_at, class: 'form-label' %>
    <%= form.datetime_select :failed_at, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :locked_by, class: 'form-label' %>
    <%= form.text_field :locked_by, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= form.label :queue, class: 'form-label' %>
    <%= form.text_field :queue, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
    <%= link_to 'Cancel', :back, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/jober_engine/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

app/views/jober_engine/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h3>All Jobs</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Priority</th>
      <th>Attempts</th>
      <th>Handler</th>
      <th>Last error</th>
      <th>Run at</th>
      <th>Locked at</th>
      <th>Failed at</th>
      <th>Locked by</th>
      <th>Queue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.priority %></td>
        <td><%= job.attempts %></td>
        <td><%= job.handler %></td>
        <td><%= job.last_error %></td>
        <td><%= job.run_at %></td>
        <td><%= job.locked_at %></td>
        <td><%= job.failed_at %></td>
        <td><%= job.locked_by %></td>
        <td><%= job.queue %></td>
        <td><%= link_to 'Show', job, class:"btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'Create Job', new_job_path, class: "btn btn-primary" %>

app/views/jober_engine/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

app/views/jober_engine/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Priority:</strong>
  <%= @job.priority %>
</p>

<p>
  <strong>Attempts:</strong>
  <%= @job.attempts %>
</p>

<p>
  <strong>Handler:</strong>
  <%= @job.handler %>
</p>

<p>
  <strong>Last error:</strong>
  <%= @job.last_error %>
</p>

<p>
  <strong>Run at:</strong>
  <%= @job.run_at %>
</p>

<p>
  <strong>Locked at:</strong>
  <%= @job.locked_at %>
</p>

<p>
  <strong>Failed at:</strong>
  <%= @job.failed_at %>
</p>

<p>
  <strong>Locked by:</strong>
  <%= @job.locked_by %>
</p>

<p>
  <strong>Queue:</strong>
  <%= @job.queue %>
</p>

<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-primary" %>
<%= link_to 'Destroy', @job, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>

app/views/layouts/jober_engine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jober engine</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "jober_engine/application", media: "all" %>

  <%= javascript_include_tag 'jober_engine/application' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <div class="row">

    <div class="col col-md">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Job Manager</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
              <%= link_to 'All Jobs', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
              <%= link_to 'Home', '/', class: 'nav-link' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="row justify-content-md-center">
      <div class="col col-md-10">
      <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>